server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  location = /api/leads {
    proxy_pass https://n8n-new-n8n.ca31ey.easypanel.host/webhook/criacao_csv_leads_v3;
    proxy_ssl_server_name on;
    proxy_http_version 1.1;
    proxy_pass_request_headers off;
    proxy_set_header Host n8n-new-n8n.ca31ey.easypanel.host;
    proxy_set_header Content-Type application/json;
    proxy_set_header Content-Length $content_length;
    proxy_set_header Connection "";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
